## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

## CVE-2021-30005
 In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.

- [https://github.com/atorralba/CVE-2021-30005-POC](https://github.com/atorralba/CVE-2021-30005-POC) :  
![starts](https://img.shields.io/github/stars/atorralba/CVE-2021-30005-POC.svg) 
![forks](https://img.shields.io/github/forks/atorralba/CVE-2021-30005-POC.svg) 
2021-05-12T11:15:44Z

